// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRvFTQi-yc1hNk8MvW5Os-_wVN3f_Yl98',
    appId: '1:437542196299:web:d934aa9ad8552bb91a69ce',
    messagingSenderId: '437542196299',
    projectId: 'smart-napper',
    authDomain: 'smart-napper.firebaseapp.com',
    storageBucket: 'smart-napper.firebasestorage.app',
    measurementId: 'G-8LH64QNTYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbyl8eLvkge41xFCuH6HFqelmxIBRSGnk',
    appId: '1:437542196299:android:a905563c426b81651a69ce',
    messagingSenderId: '437542196299',
    projectId: 'smart-napper',
    storageBucket: 'smart-napper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_38fE2bEMz0txDfsjZC9s0_9F3p-celE',
    appId: '1:437542196299:ios:b1b35175cfe3256e1a69ce',
    messagingSenderId: '437542196299',
    projectId: 'smart-napper',
    storageBucket: 'smart-napper.firebasestorage.app',
    iosBundleId: 'com.example.smartNapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_38fE2bEMz0txDfsjZC9s0_9F3p-celE',
    appId: '1:437542196299:ios:b1b35175cfe3256e1a69ce',
    messagingSenderId: '437542196299',
    projectId: 'smart-napper',
    storageBucket: 'smart-napper.firebasestorage.app',
    iosBundleId: 'com.example.smartNapper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRvFTQi-yc1hNk8MvW5Os-_wVN3f_Yl98',
    appId: '1:437542196299:web:1d3324645a3a36591a69ce',
    messagingSenderId: '437542196299',
    projectId: 'smart-napper',
    authDomain: 'smart-napper.firebaseapp.com',
    storageBucket: 'smart-napper.firebasestorage.app',
    measurementId: 'G-GYN0P5VSSD',
  );
}
